### ISSUE TITLE
Error while installing face_recognition 

### ISSUE THREAD

**Issue by Albonycal** [geerlingguy/facial_recognition#5]
Any idea how to solve this?
OS: Fedora 

``` bash
$ pip install face_recognition 
Defaulting to user installation because normal site-packages is not writeable
Collecting face_recognition
  Using cached face_recognition-1.3.0-py2.py3-none-any.whl (15 kB)
Requirement already satisfied: face-recognition-models>=0.3.0 in /home/albony/.local/lib/python3.10/site-packages (from face_recognition) (0.3.0)
Requirement already satisfied: numpy in /home/albony/.local/lib/python3.10/site-packages (from face_recognition) (1.22.0)
Collecting dlib>=19.7
  Using cached dlib-19.22.1.tar.gz (7.4 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: Click>=6.0 in /usr/lib/python3.10/site-packages (from face_recognition) (8.0.1)
Requirement already satisfied: Pillow in /usr/lib64/python3.10/site-packages (from face_recognition) (8.3.2)
Building wheels for collected packages: dlib
  Building wheel for dlib (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hv6sm3t8/dlib_fe5298ca4d1c4d969bf47d78f5f31115/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hv6sm3t8/dlib_fe5298ca4d1c4d969bf47d78f5f31115/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-xckwn549
       cwd: /tmp/pip-install-hv6sm3t8/dlib_fe5298ca4d1c4d969bf47d78f5f31115/
  Complete output (58 lines):
  running bdist_wheel
  running build
  running build_py
  package init file 'tools/python/dlib/__init__.py' not found (or not a regular file)
  running build_ext
  Building extension for Python 3.10.1 (main, Dec  9 2021, 00:00:00) [GCC 11.2.1 20211203 (Red Hat 11.2.1-7)]
  Invoking CMake setup: 'cmake /tmp/pip-install-hv6sm3t8/dlib_fe5298ca4d1c4d969bf47d78f5f31115/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-hv6sm3t8/dlib_fe5298ca4d1c4d969bf47d78f5f31115/build/lib.linux-x86_64-3.10 -DPYTHON_EXECUTABLE=/usr/bin/python3 -DCMAKE_BUILD_TYPE=Release'
  -- The C compiler identification is GNU 11.2.1
  -- The CXX compiler identification is unknown
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  CMake Error at CMakeLists.txt:14 (project):
    No CMAKE_CXX_COMPILER could be found.
  
    Tell CMake where to find the compiler by setting either the environment
    variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
    to the compiler, or to the compiler name if it is in the PATH.
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-hv6sm3t8/dlib_fe5298ca4d1c4d969bf47d78f5f31115/build/temp.linux-x86_64-3.10/CMakeFiles/CMakeOutput.log".
  See also "/tmp/pip-install-hv6sm3t8/dlib_fe5298ca4d1c4d969bf47d78f5f31115/build/temp.linux-x86_64-3.10/CMakeFiles/CMakeError.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-hv6sm3t8/dlib_fe5298ca4d1c4d969bf47d78f5f31115/setup.py", line 222, in <module>
      setup(
    File "/home/albony/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 155, in setup
      return distutils.core.setup(**attrs)
    File "/home/albony/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
      return run_commands(dist)
    File "/home/albony/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
      dist.run_commands()
    File "/home/albony/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "/home/albony/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/home/albony/.local/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/home/albony/.local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/albony/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/home/albony/.local/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/albony/.local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/albony/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-hv6sm3t8/dlib_fe5298ca4d1c4d969bf47d78f5f31115/setup.py", line 134, in run
      self.build_extension(ext)
    File "/tmp/pip-install-hv6sm3t8/dlib_fe5298ca4d1c4d969bf47d78f5f31115/setup.py", line 171, in build_extension
      subprocess.check_call(cmake_setup, cwd=build_folder)
    File "/usr/lib64/python3.10/subprocess.py", line 369, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-hv6sm3t8/dlib_fe5298ca4d1c4d969bf47d78f5f31115/tools/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-hv6sm3t8/dlib_fe5298ca4d1c4d969bf47d78f5f31115/build/lib.linux-x86_64-3.10', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: dlib, face-recognition
    Running setup.py install for dlib ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hv6sm3t8/dlib_fe5298ca4d1c4d969bf47d78f5f31115/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hv6sm3t8/dlib_fe5298ca4d1c4d969bf47d78f5f31115/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-fowsomnr/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/albony/.local/include/python3.10/dlib
         cwd: /tmp/pip-install-hv6sm3t8/dlib_fe5298ca4d1c4d969bf47d78f5f31115/
    Complete output (62 lines):
    running install
    /home/albony/.local/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_py
    package init file 'tools/python/dlib/__init__.py' not found (or not a regular file)
    running build_ext
    Building extension for Python 3.10.1 (main, Dec  9 2021, 00:00:00) [GCC 11.2.1 20211203 (Red Hat 11.2.1-7)]
    Invoking CMake setup: 'cmake /tmp/pip-install-hv6sm3t8/dlib_fe5298ca4d1c4d969bf47d78f5f31115/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-hv6sm3t8/dlib_fe5298ca4d1c4d969bf47d78f5f31115/build/lib.linux-x86_64-3.10 -DPYTHON_EXECUTABLE=/usr/bin/python3 -DCMAKE_BUILD_TYPE=Release'
    -- The C compiler identification is GNU 11.2.1
    -- The CXX compiler identification is unknown
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    CMake Error at CMakeLists.txt:14 (project):
      No CMAKE_CXX_COMPILER could be found.
    
      Tell CMake where to find the compiler by setting either the environment
      variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
      to the compiler, or to the compiler name if it is in the PATH.
    
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-install-hv6sm3t8/dlib_fe5298ca4d1c4d969bf47d78f5f31115/build/temp.linux-x86_64-3.10/CMakeFiles/CMakeOutput.log".
    See also "/tmp/pip-install-hv6sm3t8/dlib_fe5298ca4d1c4d969bf47d78f5f31115/build/temp.linux-x86_64-3.10/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-hv6sm3t8/dlib_fe5298ca4d1c4d969bf47d78f5f31115/setup.py", line 222, in <module>
        setup(
      File "/home/albony/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 155, in setup
        return distutils.core.setup(**attrs)
      File "/home/albony/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
        return run_commands(dist)
      File "/home/albony/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
        dist.run_commands()
      File "/home/albony/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "/home/albony/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/home/albony/.local/lib/python3.10/site-packages/setuptools/command/install.py", line 68, in run
        return orig.install.run(self)
      File "/home/albony/.local/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 662, in run
        self.run_command('build')
      File "/home/albony/.local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/albony/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/home/albony/.local/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/albony/.local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/albony/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-hv6sm3t8/dlib_fe5298ca4d1c4d969bf47d78f5f31115/setup.py", line 134, in run
        self.build_extension(ext)
      File "/tmp/pip-install-hv6sm3t8/dlib_fe5298ca4d1c4d969bf47d78f5f31115/setup.py", line 171, in build_extension
        subprocess.check_call(cmake_setup, cwd=build_folder)
      File "/usr/lib64/python3.10/subprocess.py", line 369, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-hv6sm3t8/dlib_fe5298ca4d1c4d969bf47d78f5f31115/tools/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-hv6sm3t8/dlib_fe5298ca4d1c4d969bf47d78f5f31115/build/lib.linux-x86_64-3.10', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hv6sm3t8/dlib_fe5298ca4d1c4d969bf47d78f5f31115/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hv6sm3t8/dlib_fe5298ca4d1c4d969bf47d78f5f31115/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-fowsomnr/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/albony/.local/include/python3.10/dlib Check the logs for full command output.
```

**Comment by IM-TechieScientist** [comment]
I'm getting the same error too.
Tried manually installing cmake , adding it to the path and installing visual studio build tools. 
Still cant get it to install :(

**Comment by coder0107git** [comment]
Try what's suggested [here](https://lists.fedoraproject.org/archives/list/users@lists.fedoraproject.org/thread/KWROF2KFNOX7BPN5LUS2DJINUMRMPJB7/).
